name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: focus
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d focus" 
          --health-interval=5s 
          --health-timeout=2s 
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      # Build your C++ binary
      - name: Build binary
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential cmake libpqxx-dev libasio-dev
          mkdir build && cd build
          cmake .. 
          make -j$(nproc)

      # Run migrations against the service-side Postgres
      - name: Apply migrations
        run: |
          psql "host=127.0.0.1 port=5432 user=user password=pass dbname=focus" \
            < migrations/001_create_tasks.sql

      # Start your service pointing at the service-networked host
      - name: Launch service
        run: |
          docker run -d --name focus-test \
            --network host \
            mydockerhubusername/focus:latest

      # Smoke-tests the health and CRUD endpoints
      - name: Smoke tests
        run: |
          # Wait for service to come up
          for i in {1..10}; do
            curl -f http://localhost:8080/healthz && break
            sleep 1
          done

          # Test POST /tasks
          curl -f -X POST http://localhost:8080/tasks \
               -H "Content-Type: application/json" \
               -d '{"name":"ci-test"}'

          # Test GET /tasks (should include the new task)
          curl -f http://localhost:8080/tasks | grep '"name":"ci-test"'

      - name: Teardown
        run: |
          docker rm -f focus-test
