name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: focus
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d focus"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libpqxx-dev libasio-dev

      - name: Configure & build
        run: |
          cmake -S . -B build
          cmake --build build -- -j$(nproc)

      - name: Apply database migrations
        run: |
          psql "host=127.0.0.1 port=5432 user=user password=pass dbname=focus" \
            < migrations/001_create_tasks.sql

      - name: Launch service
        run: |
          ./build/focus &
          sleep 3

      - name: Smoke tests
        run: |
          curl -f http://localhost:8080/healthz
          curl -f -X POST http://localhost:8080/tasks \
            -H "Content-Type: application/json" \
            -d '{"name":"ci-test"}'
          curl -f http://localhost:8080/tasks | grep '"name":"ci-test"'
